---
title: Final Prediction
author: Hannah Valencia
date: '2022-11-04'
slug: []
categories: []
tags: []
summary: "Over the past nine weeks, we have explored a multitude of variables that may impact election outcomes in an attempt to forecast the 2022 midterm election. We have learned about economic forces, polling, expert predictions, incumbency, advertising, campaigning, and more to find if they hold any predictive power, and how together in a model they may foreshadow what is to come in the results next week. In this blog, I will create a final prediction model for the House of Representatives and share its results, with the intention of reflecting on it after the election." 
---



<p><em>This blog is part of a series related to Gov 1347: Election Analytics, a course at <a href="https://www.harvard.edu/">Harvard University</a> taught by Professor <a href="http://ryandenos.com/">Ryan D. Enos</a></em>.</p>
<p><em>Over the past nine weeks, we have explored a multitude of variables that may impact election outcomes in an attempt to forecast the 2022 midterm election. We have learned about economic forces, polling, expert predictions, incumbency, advertising, campaigning, and more to find if they hold any predictive power, and how together in a model they may foreshadow what is to come in the results next week. In this blog, I will create a final prediction model for the House of Representatives and share its results, with the intention of reflecting on it after the election.</em></p>
<div id="background" class="section level3">
<h3>Background</h3>
<p>Since this class first convened in the beginning of September, we have time and time again been reminded of the shortcomings of election forecasting. Elections are fickle and there is no way to know for certain how voters will vote on election day. The experts oftentimes cannot predict what will happen, if an election will be toss-up or a landslide. There are shocks that no one sees coming, costs of voting that may be unanticipated, various biases with polling, and ever-changing political opinions that result from all sorts of issues and news. While these unknowns make forecasting very difficult, we have gained the tools over the last nine weeks that give us a good foundation to create predictions of our own for the House of Representatives midterm election.</p>
</div>
<div id="my-model-choices" class="section level3">
<h3>My Model Choices</h3>
<p>In building my model, the first choice I had was what to use as my dependent variable and the level on which to predict on. For my dependent variable, I decided to run models for both Democratic seat share and Democratic vote share to see the results of both and how they may unveil different stories about the election. I also created variables putting the vote share and seat share in terms of the incumbent party to see how incumbents perform without paying specific attention to their party affiliation, but I decided that this approach would complicate interpreting results. While we spent multiple weeks working with district-level data and forecasting each of the 435 districts, in the end I have decided to predict vote share and seat share on the national level. We have more data for these variables and do not have to rely upon things like pooling, that may produce greater margins for error. Given the insufficient district-level data, a pooled model would have allowed us to take data from neighboring, similar districts and count it as its own. However, my national model was heading in the right direction in terms of improving predictability, and the lack of district data led me to decide on a national-level final model.</p>
<p>In the first week of class, we looked at the fundamentals of election forecasting models, with predictors like the president’s party. We learned about the phenomenon that takes place in most midterms where the president’s party tends to lose seats <a href="https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/abs/introduction-forecasting-the-2018-us-midterm-elections/6BA191A0140468E022ECCE67D1CDA03B">(Campbell 2018)</a>. Following these basics, in week two we looked at how Real Disposable Income (RDI) on its own does a decent job of predicting elections. We also took a look at a slew of other economic variables, such as the Consumer Price Index (CPI), GDP growth rate, unemployment, and more. Despite the overlap between the government and the economy, most of these variables proved to be insignificant and poor predictors for the House elections. The one economic variable I will be using in my final model the unemployment rate, as it is typically a decent indicator of the health of the economy. In addition to using it on its own, I have also decided to interact it with the president’s party. The most important topics to voters vary based on their political party affiliation, and Republicans are known to weigh economic factors more heavily. Therefore, an interaction term between party and unemployment rate can provide us with more significant results than the two can separately on their own.</p>
<p>We continued on from the fundamentals and economic variables onto polling, looking at the generic ballot as well as district-level polls. When adding these polls to my model, I had limited the data to 1990 and later, justifying this with the fact that polling methods have greatly changed since 1945 when the data was first captured. It was my hope that in reducing the sample, the model would better predict recent elections. While I think this justification still makes sense, especially for district-level polling where there does not exist much data even today, I will not be limiting the data by year as severely. In my final model, the only polling data I will be using is the generic ballot, measuring which party people support without regard for specific candidates. The data I will be using goes back to 1960, which is when all the variables of my interest have data for. It would still make sense to limit the data to more recent years for the same polling reasons, but since I am only dealing with the generic ballot, I believe the changing polling methods will not hinder the predictability of the model and it will be more useful to have the longer data.</p>
<p>While we did not dedicate much time in class to discussing presidential approval ratings and their impact on elections, some classmates and I spoke about incorporating it as another form of polling that has easily accessible historical data. I gathered data on presidential approval from <a href="https://analyticscampus-gallup-com.ezp-prod1.hul.harvard.edu/Tables">Gallup Analytics</a> that date back to 1960. Polling dates varied year to year, so I decided pulled the president’s approval rating from whichever the last poll right before the election was. A few years in the 1960s and 1970s, this ended up being polls that were taken from June-August of the election year, but for most other years and especially in more recent history, the ratings are from the final weeks of October. While it would have been nice to have a specific date that the approval rating was pulled from consistently every year, I believe using the poll prior to the election will mitigate any issue.</p>
<p>Incumbency has also been a popular word throughout our class, and it is proven as a good predictor for the House of Representatives elections. Looking at the district-level data we have from 1945-2020, we find that the incumbent wins the House race about 84% of the time. Below is a bar graph showing this relationship.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>While this data is important at the district level, we learned about other incumbency phenomena that take place at a national level, such as the house flipping at midterm elections and the President’s party losing seats. Despite this incumbency data surely boasting high predictive power at the district-level, it does not provide much to us on a national-level. In a similar vein, however, rather than looking at the House majority incumbent from the year before, we can use the previous election’s vote share and seat share to predict that of the following election. I created lagged variables for both of these variables and will incorporate them into my final model, along with the President’s party variable that I previously mentioned.</p>
<p>The final variable I will be using in my model is an indicator variable for if the election takes place in a midterm year or not. From our discussions and readings, we know that different types of voters come out for midterm elections than presidential elections. We also learned in class that many Americans do not even know who their representative is. Those who vote in a midterm year are likely more involved politically and stay up-to-date with the news. I also will be interacting this term with the president’s party variable with the thought that it could account for some of the seat flipping that we historically see. Since 1955, every house flip has been the result of a midterm election <a href="https://www.reuters.com/graphics/USA-ELECTION/MIDTERMS/gdpzyzowgvw/index.html">(Reuters)</a>. This interaction term can account for the additional incumbent losses that occur during midterms but not during election years.</p>
<p>Throughout our time this semester, we have also worked with multiple other district-level variables that I will not be including in my model. We learned about advertising and the amount parties spend on advertising. In <a href="https://hollis.harvard.edu/primo-explore/fulldisplay?docid=TN_cdi_proquest_miscellaneous_881466543&amp;context=PC&amp;vid=HVD2&amp;search_scope=everything&amp;tab=everything&amp;lang=en_US">Gerber et al. 2011</a> the authors found that “televised ads have strong but short-lived effects on voting preferences”. With this in mind, along with in-class discussions about advertising data being unreliable and sometimes unavailable, I decided to forego using it in my model. Other district-level variables such as the cost of voting, ground campaigning efforts, and voter turnout I will not be adjusting to incorporate into my national model.</p>
</div>
<div id="formulas" class="section level3">
<h3>Formulas</h3>
<p>Given all the data we have considered using this semester, and after many rounds of trial and error, I have created two final models. Below are the model equations and their corresponding regression tables using the national data that we are working with.</p>
<div id="democratic-vote-share" class="section level4">
<h4>Democratic Vote Share</h4>
<p><span class="math display">\[
Democratic Vote Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Vote Share\beta_2 + President Party R\beta_3 + President Approval\beta_4 + Midterm\beta_5 + Unemployment Rate\beta_6 + President Party R * Midterm\beta_7 + President Party R * Unemployment\beta_8
\]</span></p>
<table style="text-align:center">
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
D_majorvote_pct
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
<td>
(5)
</td>
<td>
(6)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Generic Ballot Support - D
</td>
<td>
0.386<sup>***</sup>
</td>
<td>
0.354<sup>***</sup>
</td>
<td>
0.366<sup>***</sup>
</td>
<td>
0.389<sup>***</sup>
</td>
<td>
0.272<sup>***</sup>
</td>
<td>
0.229<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.099)
</td>
<td>
(0.098)
</td>
<td>
(0.093)
</td>
<td>
(0.093)
</td>
<td>
(0.083)
</td>
<td>
(0.082)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Lag House Dem VS
</td>
<td>
</td>
<td>
0.237
</td>
<td>
0.320<sup>**</sup>
</td>
<td>
0.296<sup>**</sup>
</td>
<td>
0.405<sup>***</sup>
</td>
<td>
0.426<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.147)
</td>
<td>
(0.144)
</td>
<td>
(0.142)
</td>
<td>
(0.119)
</td>
<td>
(0.119)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R
</td>
<td>
</td>
<td>
</td>
<td>
1.965<sup>**</sup>
</td>
<td>
1.905<sup>**</sup>
</td>
<td>
-0.811
</td>
<td>
-6.339<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.922)
</td>
<td>
(0.909)
</td>
<td>
(1.042)
</td>
<td>
(2.879)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Approval Rating
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-5.416
</td>
<td>
-3.627
</td>
<td>
-5.435<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(3.970)
</td>
<td>
(3.256)
</td>
<td>
(3.155)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Midterm Year
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-3.837<sup>***</sup>
</td>
<td>
-4.644<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(1.046)
</td>
<td>
(1.053)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Unemployment Rate
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-0.690<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.307)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R * Midterm Year
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
5.851<sup>***</sup>
</td>
<td>
6.793<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(1.564)
</td>
<td>
(1.565)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R * Unemployment
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
0.793<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.424)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
33.616<sup>***</sup>
</td>
<td>
22.757<sup>***</sup>
</td>
<td>
16.775<sup>*</sup>
</td>
<td>
19.685<sup>**</sup>
</td>
<td>
20.475<sup>***</sup>
</td>
<td>
27.238<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(4.809)
</td>
<td>
(8.182)
</td>
<td>
(8.204)
</td>
<td>
(8.353)
</td>
<td>
(6.756)
</td>
<td>
(7.042)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.344
</td>
<td>
0.400
</td>
<td>
0.487
</td>
<td>
0.521
</td>
<td>
0.711
</td>
<td>
0.767
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.322
</td>
<td>
0.357
</td>
<td>
0.430
</td>
<td>
0.447
</td>
<td>
0.639
</td>
<td>
0.682
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
2.674 (df = 29)
</td>
<td>
2.602 (df = 28)
</td>
<td>
2.452 (df = 27)
</td>
<td>
2.414 (df = 26)
</td>
<td>
1.951 (df = 24)
</td>
<td>
1.830 (df = 22)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
15.217<sup>***</sup> (df = 1; 29)
</td>
<td>
9.343<sup>***</sup> (df = 2; 28)
</td>
<td>
8.530<sup>***</sup> (df = 3; 27)
</td>
<td>
7.067<sup>***</sup> (df = 4; 26)
</td>
<td>
9.849<sup>***</sup> (df = 6; 24)
</td>
<td>
9.051<sup>***</sup> (df = 8; 22)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="6" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<pre><code>## 
## Call:
## lm(formula = D_majorvote_pct ~ gen_avg_dem + DemVS_prev + president_party + 
##     approval_rating + midterm * president_party + unrate + unrate * 
##     president_party, data = natldata2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.0603 -1.0010  0.2003  1.0220  2.8136 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               27.2380     7.0419   3.868 0.000832 ***
## gen_avg_dem                0.2286     0.0821   2.784 0.010813 *  
## DemVS_prev                 0.4259     0.1185   3.593 0.001617 ** 
## president_partyR          -6.3394     2.8795  -2.202 0.038480 *  
## approval_rating           -5.4353     3.1550  -1.723 0.098965 .  
## midterm                   -4.6436     1.0531  -4.409 0.000222 ***
## unrate                    -0.6904     0.3072  -2.248 0.034952 *  
## president_partyR:midterm   6.7931     1.5652   4.340 0.000263 ***
## president_partyR:unrate    0.7929     0.4240   1.870 0.074872 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.83 on 22 degrees of freedom
## Multiple R-squared:  0.767,  Adjusted R-squared:  0.6822 
## F-statistic: 9.051 on 8 and 22 DF,  p-value: 1.95e-05</code></pre>
<p>Model 6 is my final model for the Democratic Vote Share, the other models in this regression table simply show how each variable impacts and improves the model one step at a time. In this model, we see that all the variables are significant at the 0.1 significance level, and most at the 0.05 level. While approval rating and the lag of the House democratic vote share are the only variables that were not immediately significant when first added to the model, they both increased the R-squared and adjusted R-squared values, and eventually found a level of significance by the final model. Model 6 has an R-squared of 0.767 and an adjusted R-squared of 0.6822. I did some testing with other variables, but adding any of the other variables I was considering (such as percent change RDI) ended up decreasing the adjusted R-squared. The most significant variables in this model are the indicator variable for whether the election is a midterm election and the interaction between this indicator and the president’s party.</p>
</div>
<div id="deomcratic-seat-share" class="section level4">
<h4>Deomcratic Seat Share</h4>
<p><span class="math display">\[
Democratic Seat Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Seat Share\beta_2 + President Party R\beta_3 + President Approval\beta_4 + Midterm\beta_5 + Unemployment Rate\beta_6 + President Party R * Midterm\beta_7 + President Party R * Unemployment\beta_8
\]</span></p>
<table style="text-align:center">
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
DemSeatShare
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
<td>
(5)
</td>
<td>
(6)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Generic Ballot Support - D
</td>
<td>
0.876<sup>***</sup>
</td>
<td>
0.635<sup>***</sup>
</td>
<td>
0.655<sup>***</sup>
</td>
<td>
0.690<sup>***</sup>
</td>
<td>
0.500<sup>***</sup>
</td>
<td>
0.417<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.214)
</td>
<td>
(0.179)
</td>
<td>
(0.169)
</td>
<td>
(0.170)
</td>
<td>
(0.172)
</td>
<td>
(0.173)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Lag House Dem Seat Share
</td>
<td>
</td>
<td>
0.512<sup>***</sup>
</td>
<td>
0.560<sup>***</sup>
</td>
<td>
0.550<sup>***</sup>
</td>
<td>
0.624<sup>***</sup>
</td>
<td>
0.633<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.121)
</td>
<td>
(0.116)
</td>
<td>
(0.115)
</td>
<td>
(0.108)
</td>
<td>
(0.112)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R
</td>
<td>
</td>
<td>
</td>
<td>
3.403<sup>**</sup>
</td>
<td>
3.347<sup>**</sup>
</td>
<td>
-0.713
</td>
<td>
-10.078<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(1.596)
</td>
<td>
(1.580)
</td>
<td>
(2.070)
</td>
<td>
(5.857)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Approval Rating
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-8.731
</td>
<td>
-6.249
</td>
<td>
-9.768
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(7.009)
</td>
<td>
(6.410)
</td>
<td>
(6.311)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Midterm Year
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-5.101<sup>**</sup>
</td>
<td>
-6.607<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(2.064)
</td>
<td>
(2.088)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Unemployment Rate
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-1.314<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.610)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R * Midterm Year
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
8.521<sup>**</sup>
</td>
<td>
10.355<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(3.119)
</td>
<td>
(3.153)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R * Unemployment
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
1.294
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.875)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
12.723
</td>
<td>
-4.066
</td>
<td>
-9.406
</td>
<td>
-6.202
</td>
<td>
-0.016
</td>
<td>
14.566
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(10.406)
</td>
<td>
(9.158)
</td>
<td>
(8.983)
</td>
<td>
(9.257)
</td>
<td>
(8.649)
</td>
<td>
(10.662)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
<td>
31
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.365
</td>
<td>
0.614
</td>
<td>
0.670
</td>
<td>
0.688
</td>
<td>
0.766
</td>
<td>
0.807
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.344
</td>
<td>
0.586
</td>
<td>
0.633
</td>
<td>
0.640
</td>
<td>
0.707
</td>
<td>
0.736
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
5.786 (df = 29)
</td>
<td>
4.593 (df = 28)
</td>
<td>
4.327 (df = 27)
</td>
<td>
4.284 (df = 26)
</td>
<td>
3.865 (df = 24)
</td>
<td>
3.668 (df = 22)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
16.704<sup>***</sup> (df = 1; 29)
</td>
<td>
22.269<sup>***</sup> (df = 2; 28)
</td>
<td>
18.242<sup>***</sup> (df = 3; 27)
</td>
<td>
14.349<sup>***</sup> (df = 4; 26)
</td>
<td>
13.074<sup>***</sup> (df = 6; 24)
</td>
<td>
11.464<sup>***</sup> (df = 8; 22)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="6" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<p>Running the same regression again, but replacing vote share with seat share for both the dependent variable as well as the lagged independent variable, I found similar results. However, there were a couple of variables whose significance did not hold in the seat share model. We see that the variable for the president’s approval rating does not have any significance across any of the three models it is incorporated into and has very high standard errors. Additionally, the interaction between the President’s party and the unemployment rate do not hold significance in this model either. Despite these insignificant variables, their presence improves the adjusted R-squared so I have decided to leave them in. Similar to the vote share model, we again find the most significant variables to be the indicator variable for whether the election is a midterm election and the interaction between this indicator and the president’s party. In addition, this model also shows the lag of seat share to be a highly significant variable.</p>
<table style="text-align:center">
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
D_majorvote_pct
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Generic Ballot Support - D
</td>
<td>
0.671<sup>***</sup>
</td>
<td>
0.568<sup>***</sup>
</td>
<td>
0.515<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.152)
</td>
<td>
(0.122)
</td>
<td>
(0.130)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R
</td>
<td>
</td>
<td>
3.290<sup>***</sup>
</td>
<td>
4.165<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(1.058)
</td>
<td>
(1.310)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Lag House Dem VS
</td>
<td>
</td>
<td>
</td>
<td>
0.268
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.241)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
19.272<sup>**</sup>
</td>
<td>
22.578<sup>***</sup>
</td>
<td>
10.626
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(7.461)
</td>
<td>
(5.876)
</td>
<td>
(12.225)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
15
</td>
<td>
15
</td>
<td>
15
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.600
</td>
<td>
0.779
</td>
<td>
0.801
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.569
</td>
<td>
0.742
</td>
<td>
0.747
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
2.540 (df = 13)
</td>
<td>
1.967 (df = 12)
</td>
<td>
1.948 (df = 11)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
19.513<sup>***</sup> (df = 1; 13)
</td>
<td>
21.100<sup>***</sup> (df = 2; 12)
</td>
<td>
14.755<sup>***</sup> (df = 3; 11)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="3" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<table style="text-align:center">
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
DemSeatShare
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Generic Ballot Support - D
</td>
<td>
1.309<sup>***</sup>
</td>
<td>
1.206<sup>***</sup>
</td>
<td>
0.923<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.287)
</td>
<td>
(0.290)
</td>
<td>
(0.224)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
President Party - R
</td>
<td>
</td>
<td>
3.266
</td>
<td>
6.320<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(2.511)
</td>
<td>
(2.010)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Lag House Dem Seat Share
</td>
<td>
</td>
<td>
</td>
<td>
0.493<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.142)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-9.051
</td>
<td>
-5.769
</td>
<td>
-20.835<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(14.076)
</td>
<td>
(13.947)
</td>
<td>
(10.938)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
15
</td>
<td>
15
</td>
<td>
15
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.616
</td>
<td>
0.663
</td>
<td>
0.840
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.586
</td>
<td>
0.607
</td>
<td>
0.796
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
4.792 (df = 13)
</td>
<td>
4.669 (df = 12)
</td>
<td>
3.364 (df = 11)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
20.851<sup>***</sup> (df = 1; 13)
</td>
<td>
11.826<sup>***</sup> (df = 2; 12)
</td>
<td>
19.236<sup>***</sup> (df = 3; 11)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="3" style="text-align:right">
<sup><em></sup>p&lt;0.1; <sup><strong></sup>p&lt;0.05; <sup></strong></em></sup>p&lt;0.01
</td>
</tr>
</table>
<pre><code>##        fit      lwr     upr
## 1 50.20221 47.86202 52.5424</code></pre>
<pre><code>##        fit     lwr      upr
## 1 50.50952 45.7082 55.31085</code></pre>
<pre><code>##        fit      lwr      upr
## 1 47.85624 45.81439 49.89809</code></pre>
<pre><code>##        fit      lwr      upr
## 1 46.38345 42.94734 49.81955</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
</div>
