---
title: Post-Election Campaign Narrative
author: Hannah Valencia
date: '2022-12-02'
slug: []
categories: []
tags: []
summary: "In every election, expert predictions and district forecasts do not always align with the true results that we see. There could be numerous reasons for these discrepancies and in examining these types of districts, we can learn a lot about the campaigns run. I will be looking at Maine's 2nd Congressional District in hopes of understanding some important influences on this election and speculate where the forecasts may have gotten it wrong."
---

*This blog is part of a series related to Gov 1347: Election Analytics, a course at [Harvard University](https://www.harvard.edu/) taught by Professor [Ryan D. Enos](http://ryandenos.com/)*.

*In every election, expert predictions and district forecasts do not always align with the true results that we see. There could be numerous reasons for these discrepancies and in examining these types of districts, we can learn a lot about the campaigns run. I will be looking at Maine's 2nd Congressional District in hopes of understanding some important influences on this election and speculate where the forecasts may have gotten it wrong.*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# load libraries

library(tidyverse)
library(blogdown)
```

# Maine's 2nd Congressional District

During this election cycle, there were many toss-up districts across the US. One that I was following somewhat closely was Maine's 2nd Congressional District. Back in September, this particular district caught my eye because of the wide range of predictions that experts were making about it. In September, FiveThirtyEight predicted it to be a "Lean Democrat" winner, while The Economist had listed it as a "Very Likely Republican" district. Other sites such as Politico listed it as a toss-up. When so many other districts had similar predictions across all models and forecasting websites, this district was an anomaly. As the election day drew closer, the margins on some of these forecasts shrunk and reflected that it was a closer race than they initially predicted. However, up until the very end, they were still predicting different parties to win the district. Democratic candidate Jared Golden won the House race in this district, receiving 48.2% of the votes, compared to Republican Bruce Poliquin's 44.9%. I aim to examine this race more closely and uncover why some of these forecasts did not align with the actual race. 


### Demographics

Maine's Second Congressional District is the largest district east of the Mississippi River, and encompasses about 80% of the state's total land, occupying the northern area. While this district does not include Maine's largest city of Portland, it does include Bangor, Lewiston, and Auburn. It is the second-most rural district in the U.S. and the district with the second highest proportion of non-Hispanic White residents, as 72% of the population within the district live in rural areas and 94% of residents identify as non-Hispanic Whites. As of the 2020 Census, this district represents about 680,000 individuals, with a population that is 49.3% male and 50.7% female. The medium household income in this district is $51,585, making it poorer than most other New England districts. While the high school graduation rate is relatively high at 92.1%, the college graduation rate in the district falls on the lower end at around 25.3%. Another interesting characteristic about Maine's 2nd district is that it is the *only* district in all of New England that voted for Donald Trump in 2020, and only one of eight districts that voted for Trump in 2020 while being held by a Democrat. Ballotpedia also recognizes it as a battleground district in the 2016 election when incumbent Republican Bruce Poliquin defeated former State Senator Emily Ann Cain. New England is known as a rather liberal area, often going blue in most elections, but the makeup of this district in terms of its lack of diversity and rural population set it apart from other New England areas.

In Presidential elections prior to 1992, Maine as a state voted for Republican candidates. From 1992 until Trump in 2016, Maine voted for Democratic candidates every presidential election. In terms of the District's Congressional history, its representatives have shifted back and forth between Republican and Democratic for much of recent history. Jared Golden is the current representative, after having first been elected to the position in 2019. His Republican opponent in 2022's race, Bruce Poliquin, was the district's representative from 2015 until 2019, and prior to him, a Democratic representative held the position from 2003-2015. The district does not seem to have a strong voting pattern across Congresses. 

It is worth noting that in the November 8th, 2016 election, Maine voted to approve ranked-choice voting. Since then, they have conducted their statewide elections for governor, state legislature, and Congress in this manner.


### Forecasts

At the beginning of this class in September, the forecasts for Maine's 2nd Congressional District varied widely across sources. On September 9th, FiveThirtyEight forecasted Jared Golden (D) winning with a 63% chance and predicted a vote share of 49.6% Democrat to 46.9% Republican. Despite still being 2 months out from the election, this predicted vote share was fairly accurate, overestimating the Democratic share by 1.4% and overestimating the Republican share by 2.0%. One month prior to the election, on October 7th, FiveThirtyEight still had Jared Golden with a 63% chance of winning, although their predicted vote shares changed a small amount, with their models predicting 49.4% Democrats and 46.6% Republican, getting slightly closer to actual vote shares seen in the election. Right before the election, on November 6th, FiveThirtyEight's models still had Jared Golden favored with a 62% chance of winning. Again their vote shares shifted slightly, to 49.3% Democrat and 47.2% Republican. While the Democratic vote prediction got 0.1% closer to the actual vote share, the Republican vote share just before the election was farther off than it had been a month previously. Some of this likely has to do with the share of third party votes being higher than expected. Tiffany Bond, the Independent running against Golden and Poliquin, received 6.9% of the vote, which is higher than the 3.5% predicted by FiveThirtyEight in the days before the election. From September up until the election, FiveThirtyEight's model had the district coded as "Lean Democrat", which coincides with the results that we ended up seeing. Overall, FiveThrityEight's model was a solid predictor for the district, acknowledging the closeness of the race by having it coded as a "Lean" state, and coming pretty close with the winning party's vote share. The one place where they deviated from observed results was in the vote share of the third party, which may be underestimated in polling given the small population that do vote for this candidate.

Now turning to the other major source for House Election Forecasts: The Economist. As of September 12th, 2022, The Economist's forecast listed Maine's 2nd Congressional District as "Very Likely Republican", reporting Bruce Poliquin's chance of winning at 90%. At this time they also predicted both the Democrats and Republicans of winning 48-52% of the vote share nationwide, which is not very meaningful and much less precise than FiveThrityEight's predictions. In their model, they do not predict vote shares by district. By one month prior to the election, on October 7th, The Economist changed their prediction to "Likely" Republican for this district. At this time their model predicted Bruce Poliquin had a 66% chance to win - similar to the 62% likelihood predicted by FiveThirtyEight, but with the opposite candidate. This decline in certainty of Poliquin winning over such a short period of time, a 24 percentage-point decline, is very large. I am interested in any changes in Poliquin's campaign that led to this sharp decline in chance of winning by The Economist's model, given that a month prior that had it as a "very likely" seat for Republicans. Right before the election on November 7th, The Economist again changed the classification of the district, changing it to "uncertain" and predicting that Jared Golden had a 56% chance of winning, changing the candidate in addition to the likelihood classification. While we saw stability in FiveThirtyEight's model over the months leading up the election, The Economist's forecasting model changed a lot over the same time frame. I would be interested to see how their models differed and hopefully identify where this drastic change in predictions stems from.






























