<!DOCTYPE html>
<html lang="en-us">
    <head>
		
		
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Post-Election Reflection &middot; My New Hugo Site</title>

		
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/fonts.css">
		
		<link rel="icon" href="/favicon.ico"/>
		<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">

		
		<link href="" rel="alternate" type="application/rss+xml" title="My New Hugo Site" />

		<script src="/js/darkmode.js"></script>
	</head>

    <body>
        		<nav class="nav">
			<div class="nav-container">
				<a href="/">
					
						<h2 class="nav-title">My New Hugo Site</h2>
					
				</a>
				<ul>
    
    
</ul>
			</div>
		</nav>




    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    
        <div id="darkModeToggle" onclick="toggleDarkMode()">
  &#9680; 
</div>

        

<main>
	


        <div class="post">
		<div class="post-info">
    <span>Written by</span>
        Hannah Valencia
        <br>
        <span>on&nbsp;</span><time datetime="2022-11-18 00:00:00 &#43;0000 UTC">November 18, 2022</time>
</div>

		<h1 class="post-title">Post-Election Reflection</h1>
<div class="post-line"></div>

		

		


<p><em>This blog is part of a series related to Gov 1347: Election Analytics, a course at <a href="https://www.harvard.edu/">Harvard University</a> taught by Professor <a href="http://ryandenos.com/">Ryan D. Enos</a></em>.</p>
<p><em>On Tuesday, November 8th, eligible Americans voted in the midterm elections for candidates who will make up the 118th Congress. Prior to the election, we had created forecasting models in an attempt to determine who would win the House of Representatives, at the district-level, national-level, or both. In this post I will reflect on the predictions made, my model’s performance, and comment on the election overall.</em></p>
<p>Using the knowledge I gained this semester about election forecasting, I created multiple models to predict the outcome of the 2022 House of Representatives election. I looked at both seat share and vote share, and created two models for each: one using data across all election years, and one using the data for only midterm years. We had the opportunity to work with both national-level and seat-level data, but all of my final models used the data at the national-level for reasons I outlined in my <a href="https://h-valencia.github.io/Election-Analytics-Blog/post/2022-11-04-final-prediction/">Final Prediction Blog</a>.</p>
<p>As a refresher, here are the predictions from my four models and the actual results of the election as of November 21st, 2022:</p>
<p><strong>Model 1:</strong> Democratic Vote Share using all years
yhat = 50.20% , 95% CI (47.86, 52.54)
y = 47.59%</p>
<p><strong>Model 2:</strong> Democratic Seat Share using all years
yhat = 50.51% , 95% CI (45.71, 55.31)
y = 49.30%</p>
<p><strong>Model 3:</strong> Democratic Vote Share using midterm years
yhat = 47.86% , 95% CI (45.81, 49.90)
y = 47.59%</p>
<p><strong>Model 4:</strong> Democratic Seat Share using midterm years
yhat = 46.38% , 95% CI (42.95, 49.82)
y = 49.30%</p>
<p>To start assessing the post-election accuracy of these models and reflect on their prediction capabilities, I have created four graphs below with the actual versus predicted results each year. In my Final Prediction Blog, these graphs had the 2022 predictions as a point along the regression line of the model with both the x and y value equaling the model’s prediction for the 2022 election. If its prediction had been completely accurate, this point would have stayed along the regression line. In the plots below, I have added a blue point that represents the actual election results as of November 21st, 2022, when 430 of the House seats have been decided. According to the Cook Political Report, Democrats have won 212 seats at this point, and Republicans have won 218 - a democratic seat share of 49.30%. The Cook Political Report also has counted a total of 50,464,746 votes for Democrats versus 53,948,354 for Republicans - giving a democratic vote share of 47.59%. In the graphs below, our predicted values have not changed since the models have not been adjusted at all from the final prediction, however the new y-value of the point shows the actual outcome. The distance between this point and the regression line shows the accuracy of our prediction, with a point closer to the line representing results that came very close to our prediction, and points further from the line representing a less-accurate prediction.</p>
<div id="model-1" class="section level4">
<h4>Model 1</h4>
<p><span class="math display">\[
Democratic Vote Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Vote Share\beta_2 + President Party R\beta_3 + President Approval\beta_4 + Midterm\beta_5 + Unemployment Rate\beta_6 + President Party R * Midterm\beta_7 + President Party R * Unemployment\beta_8
\]</span></p>
<p><img src="http://example.org/post/2022-11-18-post-election-reflection/index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>The graph above shows the model for vote share across all election years, both midterm and presidential. As we can see, the predicted vote share for the 2022 House was 50.2022%, or practically a tie between the Democrats and Republicans. We know that in recent history it is not uncommon for the vote share to be relatively close, even if one party comes away winning the majority of the seats – or in the case of a presidential election, the electoral votes – so this prediction seemed reasonable prior to the election. The actual democratic vote share was around 47.6%, which fell just outside of my prediction’s 95% Confidence Interval of (47.8, 52.54) that is represented by the grey dotted line on the plot. The fact that the actual vote share was <em>not</em> in the 95% confidence interval puzzles me a bit, as it makes me question whether this election fell to an extreme, or if this model was not the best predictor of the election since we would have hoped the error margins would be wide enough to capture this result. Despite these questions and falling outside of the confidence interval, my prediction is actually not that far off from the actual results, overestimating the vote share by 2.6122 percentage points.</p>
</div>
<div id="model-2" class="section level4">
<h4>Model 2</h4>
<p><span class="math display">\[
Democratic Seat Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Seat Share\beta_2 + President Party R\beta_3 + President Approval\beta_4 + Midterm\beta_5 + Unemployment Rate\beta_6 + President Party R * Midterm\beta_7 + President Party R * Unemployment\beta_8
\]</span></p>
<p><img src="http://example.org/post/2022-11-18-post-election-reflection/index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
This model of seat share using data across all the election years fared much better than the one above, and produced a prediction that was very close to the results we actually saw, with the model overestimating the seat share by just 1.21 percentage points. In this model, the results also fell within the 95% confidence interval, unlike above. In my final election prediction blog, I noted that this model had the highest R-squared value, and these results resemble that accuracy.</p>
</div>
<div id="model-3" class="section level4">
<h4>Model 3</h4>
<p><span class="math display">\[
Democratic Vote Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Vote Share\beta_2 + President Party R\beta_3
\]</span></p>
<p><img src="http://example.org/post/2022-11-18-post-election-reflection/index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>In the graph above, this model used only the midterm election years to regress on Democratic vote share and the results were extremely accurate. This model also had a high R-squared of 0.89, and it only overestimated the results by 0.27 percentage points. This was the most accurate prediction out of all four models, which surprised me a bit. In my initial predictions, I thought that these midterm year models would be less predictive, as they have fewer data points to work off of, and included fewer independent variables. While this midterm model was an accurate predictor, the other midterm model did not perform as well.</p>
</div>
<div id="model-4" class="section level4">
<h4>Model 4</h4>
<p><span class="math display">\[
Democratic Seat Share = \beta_0 + Generic Ballot Democrat\beta_1 + Lag House Dem Seat Share\beta_2 + President Party R\beta_3
\]</span></p>
<p><img src="http://example.org/post/2022-11-18-post-election-reflection/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>This midterm model underestimated the actual democratic seat share of the election by 2.92 percentage points. This was the only model that <em>underestimated</em> the dependent variable, however the prediction did still fall within the 95% confidence interval. This was the largest percentage-point difference between the prediction and the result across all four of the models, but I did expect this as the R-squared value is also the lowest of the four.</p>
<p>Looking at the results across all four models, it seems that using only the midterm years’ model for democratic vote share is more predictive than if we had used the model that spans all elections, while we see the opposite for democratic seat share - with the more predictive model being the one that uses all the elections. One reason I speculate this may be is because there is a different voter population during midterm years than election years, which has a strong affect on the vote share while the seats are more representative of the areas demographics. The number of voters in midterm years differs dramatically from the number that vote in election years - with presidential election years generating turnouts of around 50-60% and midterm elections only generating about 40% turnout. Since the number of voters participating differs between the two, it may be harder for the models that use all the years’ data to accurately predict the vote share down to a hundredth of a percentage point, as we are looking at here. If this speculation is somewhat correct, this would mean that incorporating voter turnout in to the model may have improved the accuracy. I will check this below by running the vote share model across all years and adding turnout as an independent variable to see if this improves the accuracy of the model.</p>
<pre><code>## 
## &lt;table style=&quot;text-align:center&quot;&gt;&lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot;&gt;&lt;em&gt;Dependent variable:&lt;/em&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot;&gt;D_majorvote_pct&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1)&lt;/td&gt;&lt;td&gt;(2)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Generic Ballot Support - D&lt;/td&gt;&lt;td&gt;0.229&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.246&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.082)&lt;/td&gt;&lt;td&gt;(0.088)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Lag House Dem VS&lt;/td&gt;&lt;td&gt;0.426&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.427&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.119)&lt;/td&gt;&lt;td&gt;(0.120)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R&lt;/td&gt;&lt;td&gt;-6.339&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-6.054&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(2.879)&lt;/td&gt;&lt;td&gt;(2.961)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Approval Rating&lt;/td&gt;&lt;td&gt;-5.435&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-5.485&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(3.155)&lt;/td&gt;&lt;td&gt;(3.203)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Midterm Year&lt;/td&gt;&lt;td&gt;-4.644&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-5.561&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1.053)&lt;/td&gt;&lt;td&gt;(1.866)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Unemployment Rate&lt;/td&gt;&lt;td&gt;-0.690&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-0.678&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.307)&lt;/td&gt;&lt;td&gt;(0.312)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R * Midterm Year&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;-0.054&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;(0.090)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R * Unemployment&lt;/td&gt;&lt;td&gt;6.793&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;6.839&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1.565)&lt;/td&gt;&lt;td&gt;(1.590)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Constant&lt;/td&gt;&lt;td&gt;0.793&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.731&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.424)&lt;/td&gt;&lt;td&gt;(0.443)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Constant&lt;/td&gt;&lt;td&gt;27.238&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;29.460&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(7.042)&lt;/td&gt;&lt;td&gt;(8.049)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Observations&lt;/td&gt;&lt;td&gt;31&lt;/td&gt;&lt;td&gt;31&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.767&lt;/td&gt;&lt;td&gt;0.771&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Adjusted R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.682&lt;/td&gt;&lt;td&gt;0.673&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Residual Std. Error&lt;/td&gt;&lt;td&gt;1.830 (df = 22)&lt;/td&gt;&lt;td&gt;1.857 (df = 21)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;F Statistic&lt;/td&gt;&lt;td&gt;9.051&lt;sup&gt;***&lt;/sup&gt; (df = 8; 22)&lt;/td&gt;&lt;td&gt;7.852&lt;sup&gt;***&lt;/sup&gt; (df = 9; 21)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;em&gt;Note:&lt;/em&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot; style=&quot;text-align:right&quot;&gt;&lt;sup&gt;*&lt;/sup&gt;p&lt;0.1; &lt;sup&gt;**&lt;/sup&gt;p&lt;0.05; &lt;sup&gt;***&lt;/sup&gt;p&lt;0.01&lt;/td&gt;&lt;/tr&gt;
## &lt;/table&gt;</code></pre>
<p>Adding turnout to the model decreases the adjusted R-squared and it is an insignificant variable, however I will estimate a prediction using this model anyways to see how it performs. In order to make a prediction using the turnout model, I have estimated turnout for 2022 using the estimated 2021 CVAP and the number of counted votes for 2022 as reported by the Cook Political Report on November 21st, 2022. This estimates the turnout to be around 41%, which falls in line with our typical midterm election turnout numbers, and we will proceed with using it.</p>
<pre><code>##        fit      lwr      upr
## 1 52.36448 44.50132 60.22765</code></pre>
<p>Looking at the prediction using this model, we see that the point estimate comes up with a democratic vote share of 52.36%, compared to the 50.20% we predicted in the model <em>without</em> turnout. This is even farther away from the actual results of the 2022 election, and therefore discredits my hypothesis that turnout could account for the difference in the vote share across all years model versus the model that only looks at midterm years.</p>
<p>Another hypothesis that I have as to why the model across all years for vote share could have not performed as well relative to its midterm-year counterpart is that I did not account for any shocks, which may have made a bigger difference this year than in previous history. In class, we looked at shocks such as Dobbs v. Jackson on the generic ballot, as well as discussing other shocks such as the Clinton emails, and inflation. While in that week’s investigation, we found that shocks did not have lasting effects on voter behavior, and often were not big enough issues to sway a significant amount of voters one way or another. This year may have been different. The Dobbs v. Jackson decision is a landmark in taking away women’s rights to health care, and this is something that is not forgotten easily. While other shocks may not have had lasting effects – and we even saw the Dobbs decision’s effect on the generic ballot dwindle over time – I think this may have been a stronger factor in voter’s decisions than I would have thought. This may have swayed voters more left, thus increasing the share of President’s party votes in this midterm year. It is worth noting, however, that my initial prediction does estimate a vote share that is higher for Democrats than what we actually see so if this hypothesis were completely correct, we would likely see even <em>higher</em> democratic vote share, while a more accurate prediction would output a <em>lower</em> democratic vote share. This explanation may not be the accurate one for this model, but it is still known that the behavior of this election was less like a midterm.</p>
<p>We learned that in most midterm years, the President’s party will lose a lot of seats in the House of Representatives, and receive less vote share, and this was expected to happen again this year. However, as mentioned, this trend did not persist this year. While the limitations and difficulties with trying to measure the effect of a shock on an election remain, I will try to test the more general hypothesis that this year behaved less like a midterm year by removing the midterm year indicator variable and its interaction with the President’s party variable. I will repeat the steps from above and re-evaluate the performance of the model.</p>
<pre><code>## 
## &lt;table style=&quot;text-align:center&quot;&gt;&lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot;&gt;&lt;em&gt;Dependent variable:&lt;/em&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot;&gt;D_majorvote_pct&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1)&lt;/td&gt;&lt;td&gt;(2)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Generic Ballot Support - D&lt;/td&gt;&lt;td&gt;0.229&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.246&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.082)&lt;/td&gt;&lt;td&gt;(0.088)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Lag House Dem VS&lt;/td&gt;&lt;td&gt;0.426&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.427&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.119)&lt;/td&gt;&lt;td&gt;(0.120)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R&lt;/td&gt;&lt;td&gt;-6.339&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-6.054&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(2.879)&lt;/td&gt;&lt;td&gt;(2.961)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Approval Rating&lt;/td&gt;&lt;td&gt;-5.435&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-5.485&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(3.155)&lt;/td&gt;&lt;td&gt;(3.203)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Midterm Year&lt;/td&gt;&lt;td&gt;-4.644&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-5.561&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1.053)&lt;/td&gt;&lt;td&gt;(1.866)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Unemployment Rate&lt;/td&gt;&lt;td&gt;-0.690&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;-0.678&lt;sup&gt;**&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.307)&lt;/td&gt;&lt;td&gt;(0.312)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R * Midterm Year&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;-0.054&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;(0.090)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;President Party - R * Unemployment&lt;/td&gt;&lt;td&gt;6.793&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;6.839&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(1.565)&lt;/td&gt;&lt;td&gt;(1.590)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Constant&lt;/td&gt;&lt;td&gt;0.793&lt;sup&gt;*&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.731&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(0.424)&lt;/td&gt;&lt;td&gt;(0.443)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Constant&lt;/td&gt;&lt;td&gt;27.238&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;29.460&lt;sup&gt;***&lt;/sup&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;(7.042)&lt;/td&gt;&lt;td&gt;(8.049)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Observations&lt;/td&gt;&lt;td&gt;31&lt;/td&gt;&lt;td&gt;31&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.767&lt;/td&gt;&lt;td&gt;0.771&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Adjusted R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;&lt;td&gt;0.682&lt;/td&gt;&lt;td&gt;0.673&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;Residual Std. Error&lt;/td&gt;&lt;td&gt;1.830 (df = 22)&lt;/td&gt;&lt;td&gt;1.857 (df = 21)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;F Statistic&lt;/td&gt;&lt;td&gt;9.051&lt;sup&gt;***&lt;/sup&gt; (df = 8; 22)&lt;/td&gt;&lt;td&gt;7.852&lt;sup&gt;***&lt;/sup&gt; (df = 9; 21)&lt;/td&gt;&lt;/tr&gt;
## &lt;tr&gt;&lt;td colspan=&quot;3&quot; style=&quot;border-bottom: 1px solid black&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style=&quot;text-align:left&quot;&gt;&lt;em&gt;Note:&lt;/em&gt;&lt;/td&gt;&lt;td colspan=&quot;2&quot; style=&quot;text-align:right&quot;&gt;&lt;sup&gt;*&lt;/sup&gt;p&lt;0.1; &lt;sup&gt;**&lt;/sup&gt;p&lt;0.05; &lt;sup&gt;***&lt;/sup&gt;p&lt;0.01&lt;/td&gt;&lt;/tr&gt;
## &lt;/table&gt;</code></pre>
<pre><code>##        fit      lwr      upr
## 1 48.81535 43.23659 54.39412</code></pre>
<p>In removing these two variables, the adjusted R-squared decreases by 0.26, which is a fairly significant amount. In addition, most of the variables also lose their significance after removal. However, the point prediction using this model is 48.82% of the democratic vote share, compared to the 50.20% in our original model. This is much closer to the actual democratic vote share of 47.6%, but the 95% confidence interval also gets wider when adjusting the model in this way. While I cannot say for sure that this election acted differently than other midterm elections because of the shock of Dobbs v. Jackson, the inclusion of the midterm variable does seem to shift the data more positively towards Democrats, suprassing the vote share we actually see.</p>
</div>


		
	</div>

	<div class="pagination">
		<a href="/post/2022-11-04-final-prediction/" class="left arrow">&#8592;</a>

		<a href="#" class="top">Top</a>
	</div>
</main>


        		<footer>
			
			<span>
			&copy; <time datetime="2022-11-22 00:52:32.21522 -0500 EST m=&#43;4.152268647">2022</time> . Made with <a href='https://gohugo.io'>Hugo</a> using the <a href='https://github.com/EmielH/tale-hugo/'>Tale</a> theme.
			</span>
		</footer>

    </body>
</html>
